name: Deploy to Azure Container Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_CONTAINER_APP_NAME: solana-trading-bot
  AZURE_RESOURCE_GROUP: rg-bot
  AZURE_REGISTRY: solanatradingreg.azurecr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: solanatradingreg.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push container image
      run: |
        docker build . -t solanatradingreg.azurecr.io/solana-trading-bot:${{ github.sha }}
        docker build . -t solanatradingreg.azurecr.io/solana-trading-bot:latest
        docker push solanatradingreg.azurecr.io/solana-trading-bot:${{ github.sha }}
        docker push solanatradingreg.azurecr.io/solana-trading-bot:latest
    
    - name: Deploy to Container Apps
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update \
            --name solana-trading-bot \
            --resource-group rg-bot \
            --image solanatradingreg.azurecr.io/solana-trading-bot:${{ github.sha }}
