name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Login to Azure Container Registry
      - name: Docker login
        run: |
          echo ${{ secrets.SOLANATRADINGBOT_REGISTRY_PASSWORD }} | docker login solanatradingreg.azurecr.io \
            -u ${{ secrets.SOLANATRADINGBOT_REGISTRY_USERNAME }} --password-stdin

      # 4. Build and push Docker image
      - name: Build and Push image
        run: |
          docker build -t solanatradingreg.azurecr.io/solana-trading-bot:latest .
          docker push solanatradingreg.azurecr.io/solana-trading-bot:latest

      # 5. Deploy to Azure Container App
      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: solanatradingreg
          containerAppName: solana-trading-bot
          resourceGroup: rg-bot
          imageToDeploy: solanatradingreg.azurecr.io/solana-trading-bot:latest
