name: agent
on: push
permissions: { id-token: write, contents: read }

jobs:
  deploy:
    permissions: { id-token: write, contents: read }
    runs-on: ubuntu-latest
    env: { IMAGE_NAME: trading-bot, TAG: latest }
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:  ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login --name $(echo ${{ secrets.ACR_LOGIN_SERVER }} | cut -d. -f1)

      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Update Container App
        run: |
          az containerapp update \
            -g "${{ secrets.RESOURCE_GROUP }}" \
            -n "${{ secrets.CONTAINERAPP_NAME }}" \
