name: Deploy to Azure Container Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_CONTAINER_APP_NAME: tradingbot-app
  AZURE_RESOURCE_GROUP: trading-bot-rg
  AZURE_REGISTRY: tradingbotacr251.azurecr.io
  AZURE_CORE_OUTPUT: none

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name tradingbotacr251

      - name: Build and push container image
        run: |
          docker build . -t ${{ env.AZURE_REGISTRY }}/solana-trading-bot:${{ github.sha }}
          docker build . -t ${{ env.AZURE_REGISTRY }}/solana-trading-bot:latest
          docker push ${{ env.AZURE_REGISTRY }}/solana-trading-bot:${{ github.sha }}
          docker push ${{ env.AZURE_REGISTRY }}/solana-trading-bot:latest

      - name: Deploy to Container Apps
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update \
            --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --image ${{ env.AZURE_REGISTRY }}/solana-trading-bot:${{ github.sha }}
