name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Container App secrets
        uses: azure/cli@v1
        with:
          inlineScript: |
            az containerapp secret set \
              --name ${{ secrets.CONTAINERAPP_NAME }} \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --secrets \
                TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
                TELEGRAM_WEBHOOK_URL=${{ secrets.TELEGRAM_WEBHOOK_URL }} \
                COSMOS_DB_CONNECTION_STRING=${{ secrets.COSMOS_DB_CONNECTION_STRING }} \
                SOLANA_RPC_URL=${{ secrets.SOLANA_RPC_URL }}

      - name: Build, Push, and Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          # Use explicit registry credentials from secrets
          registryUrl: ${{ secrets.ACR_LOGIN_SERVER }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}

          imageToBuild: ${{ secrets.ACR_LOGIN_SERVER }}/solana-trading-bot:${{ github.sha }}
          dockerfilePath: ./Dockerfile
          containerAppName: ${{ secrets.CONTAINERAPP_NAME }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          targetPort: 3000
          ingress: external
          environmentVariables: |
            TELEGRAM_BOT_TOKEN=secretref:TELEGRAM_BOT_TOKEN
            TELEGRAM_MODE=webhook
            TELEGRAM_WEBHOOK_URL=secretref:TELEGRAM_WEBHOOK_URL
            COSMOS_DB_CONNECTION_STRING=secretref:COSMOS_DB_CONNECTION_STRING
            SOLANA_RPC_URL=secretref:SOLANA_RPC_URL
