name: Trigger auto deployment for tradingbot-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tradingbot-app-AutoDeployTrigger-7a199224-8e8b-4e66-a06d-7a5557e0623f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TRADINGBOTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TRADINGBOTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TRADINGBOTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: tradingbotacr8251.azurecr.io
          registryUsername: ${{ secrets.TRADINGBOTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TRADINGBOTAPP_REGISTRY_PASSWORD }}
          containerAppName: tradingbot-app
          resourceGroup: trading-bot-rg
          imageToBuild: tradingbotacr8251.azurecr.io/tradingbot-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


